
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin123@kokbatasi-db.0ltpmeg.mongodb.net/?retryWrites=true&w=majority&appName=kokbatasi-db
      - PORT=5000
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=https://kokbatasi.onrender.com
    volumes:
      - ./frontend:/app
    restart: always
